- name: fetch
  url: https://www.fetch.com

- name: SlowAPI
  url: https://httpstat.us/200?sleep=1000

- name: WithHeaders
  url: https://httpbin.org/headers

  method: GET
  headers:
    X-Test: MyValue
